# Generated by Django 6.0 on 2026-05-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('food', 'Ingredientes'), ('rent', 'Aluguel'), ('employee', 'Funcionários'), ('water', 'Água'), ('energy', 'Energia'), ('other', 'Outros')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
