# Generated by Django 6.0 on 2026-06-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
