# Generated by Django 6.0 on 2026-06-27 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_ingredient_cost_per_unit'),
        ('products', '0005_product_uses_recipe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productingredient',
            unique_together={('product', 'ingredient')},
        ),
    ]
