# Generated by Django 6.0 on 2026-06-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productstockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uses_recipe',
            field=models.BooleanField(default=False),
        ),
    ]
